apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-kafka-connect
  namespace: kafka-connect
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: kafka-connect-deployment
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 90  
