apiVersion: v1
data:
  filter-jira-reports-deployment.conf: |
    [FILTER]
        Name                kubernetes
        Match               jira-reports-deployment.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  filter-api-domain1-java-deployment.conf: |
    [FILTER]
        Name                kubernetes
        Match               api-domain1-java-deployment.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  filter-api-domain1-javaqa-deployment.conf: |
    [FILTER]
        Name                kubernetes
        Match               api-domain1-javaqa-deployment.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  filter-api-domain1-javastg-deployment.conf: |
    [FILTER]
        Name                kubernetes
        Match               api-domain1-javastg-deployment.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  filter-api-domain1-domain1qa-deployment.conf: |
    [FILTER]
        Name                kubernetes
        Match               api-domain1-domain1qa-deployment.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  filter-api-domain1-domain1stg-deployment.conf: |
    [FILTER]
        Name                kubernetes
        Match               api-domain1-domain1stg-deployment.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  filter-api-domain1auto-java-deployment.conf: |
    [FILTER]
        Name                kubernetes
        Match               api-domain1auto-java-deployment.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  filter-api-domain2-java-deployment.conf: |
    [FILTER]
        Name                kubernetes
        Match               api-domain2-java-deployment.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  filter-api-domain2-javaqa-deployment.conf: |
    [FILTER]
        Name                kubernetes
        Match               api-domain2-javaqa-deployment.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  filter-api-domain2-javastg-deployment.conf: |
    [FILTER]
        Name                kubernetes
        Match               api-domain2-javastg-deployment.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  filter-api-domain2auto-java-deployment.conf: |
    [FILTER]
        Name                kubernetes
        Match               api-domain2auto-java-deployment.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-jira-reports-deployment.conf
    @INCLUDE filter-jira-reports-deployment.conf
    @INCLUDE output-jira-reports-deployment.conf
    @INCLUDE input-api-domain1auto-java-deployment.conf
    @INCLUDE filter-api-domain1auto-java-deployment.conf
    @INCLUDE output-api-domain1auto-java-deployment.conf
    @INCLUDE input-api-domain1-java-deployment.conf
    @INCLUDE filter-api-domain1-java-deployment.conf
    @INCLUDE output-api-domain1-java-deployment.conf
    @INCLUDE input-api-domain1-javaqa-deployment.conf
    @INCLUDE filter-api-domain1-javaqa-deployment.conf
    @INCLUDE output-api-domain1-javaqa-deployment.conf
    @INCLUDE input-api-domain1-javastg-deployment.conf
    @INCLUDE filter-api-domain1-javastg-deployment.conf
    @INCLUDE output-api-domain1-javastg-deployment.conf
    @INCLUDE input-api-domain1-domain1stg-deployment.conf
    @INCLUDE filter-api-domain1-domain1stg-deployment.conf
    @INCLUDE output-api-domain1-domain1stg-deployment.conf
    @INCLUDE input-api-domain2auto-java-deployment.conf
    @INCLUDE filter-api-domain2auto-java-deployment.conf
    @INCLUDE output-api-domain2auto-java-deployment.conf
    @INCLUDE input-api-domain2-java-deployment.conf
    @INCLUDE filter-api-domain2-java-deployment.conf
    @INCLUDE output-api-domain2-java-deployment.conf
    @INCLUDE input-api-domain2-javaqa-deployment.conf
    @INCLUDE filter-api-domain2-javaqa-deployment.conf
    @INCLUDE output-api-domain2-javaqa-deployment.conf
    @INCLUDE input-api-domain2-javastg-deployment.conf
    @INCLUDE filter-api-domain2-javastg-deployment.conf
    @INCLUDE output-api-domain2-javastg-deployment.conf
  input-jira-reports-deployment.conf: |
    [INPUT]
        Name              tail
        Tag               jira-reports-deployment.*
        Path              /var/log/containers/jira-reports-deployment*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    
  input-api-domain1-java-deployment.conf: |
    [INPUT]
        Name              tail
        Tag               api-domain1-java-deployment.*
        Path              /var/log/containers/api-domain1-java-deployment*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-api-domain1-javaqa-deployment.conf: |
    [INPUT]
        Name              tail
        Tag               api-domain1-javaqa-deployment.*
        Path              /var/log/containers/api-domain1-javaqa-deployment*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-api-domain1-javastg-deployment.conf: |
    [INPUT]
        Name              tail
        Tag               api-domain1-javastg-deployment.*
        Path              /var/log/containers/api-domain1-javastg-deployment*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-api-domain1-domain1qa-deployment.conf: |
    [INPUT]
        Name              tail
        Tag               api-domain1-domain1qa-deployment.*
        Path              /var/log/containers/api-domain1-domain1qa-deployment*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-api-domain1-domain1stg-deployment.conf: |
    [INPUT]
        Name              tail
        Tag               api-domain1-domain1stg-deployment.*
        Path              /var/log/containers/api-domain1-domain1stg-deployment*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-api-domain1auto-java-deployment.conf: |
    [INPUT]
        Name              tail
        Tag               api-domain1auto-java-deployment.*
        Path              /var/log/containers/api-domain1auto-java-deployment*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-api-domain2-java-deployment.conf: |
    [INPUT]
        Name              tail
        Tag               api-domain2-java-deployment.*
        Path              /var/log/containers/api-domain2-java-deployment*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-api-domain2-javaqa-deployment.conf: |
    [INPUT]
        Name              tail
        Tag               api-domain2-javaqa-deployment.*
        Path              /var/log/containers/api-domain2-javaqa-deployment*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-api-domain2-javastg-deployment.conf: |
    [INPUT]
        Name              tail
        Tag               api-domain2-javastg-deployment.*
        Path              /var/log/containers/api-domain2-javastg-deployment*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  input-api-domain2auto-java-deployment.conf: |
    [INPUT]
        Name              tail
        Tag               api-domain2auto-java-deployment.*
        Path              /var/log/containers/api-domain2auto-java-deployment*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
 

  output-jira-reports-deployment.conf: |
    [OUTPUT]
        Name            es
        Match           jira-reports-deployment.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix jira-reports-deployment

  output-api-domain1-java-deployment.conf: |
    [OUTPUT]
        Name            es
        Match           api-domain1-java-deployment.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix api-domain1-java-deployment
  output-api-domain1-javaqa-deployment.conf: |
    [OUTPUT]
        Name            es
        Match           api-domain1-javaqa-deployment.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix api-domain1-javaqa-deployment
  output-api-domain1-javastg-deployment.conf: |
    [OUTPUT]
        Name            es
        Match           api-domain1-javastg-deployment.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix api-domain1-javastg-deployment
  output-api-domain1-domain1qa-deployment.conf: |
    [OUTPUT]
        Name            es
        Match           api-domain1-domain1qa-deployment.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix api-domain1-domain1qa-deployment
  output-api-domain1-domain1stg-deployment.conf: |
    [OUTPUT]
        Name            es
        Match           api-domain1-domain1stg-deployment.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix api-domain1-domain1stg-deployment
  output-api-domain1auto-java-deployment.conf: |
    [OUTPUT]
        Name            es
        Match           api-domain1auto-java-deployment.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix api-domain1auto-java-deployment
  output-api-domain2-java-deployment.conf: |
    [OUTPUT]
        Name            es
        Match           api-domain2-java-deployment.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix api-domain2-java-deployment
  output-api-domain2-javaqa-deployment.conf: |
    [OUTPUT]
        Name            es
        Match           api-domain2-javaqa-deployment.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix api-domain2-javaqa-deployment
  output-api-domain2-javastg-deployment.conf: |
    [OUTPUT]
        Name            es
        Match           api-domain2-javastg-deployment.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix api-domain2-javastg-deployment
  output-api-domain2auto-java-deployment.conf: |
    [OUTPUT]
        Name            es
        Match           api-domain2auto-java-deployment.*
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False
        Type  flb_type
        Time_Key @timestamp
        Logstash_Prefix api-domain2auto-java-deployment
    parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<domain2>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<domain2>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<domain2>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        # http://rubular.com/r/tjUt3Awgg4
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-18T19:14:14Z"
  labels:
    k8s-app: fluent-bit
  name: fluent-bit-config
  namespace: fluentbit
  resourceVersion: "36376713"
  selfLink: /api/v1/namespaces/fluentbit/configmaps/fluent-bit-config
  uid: 9049b51c-0572-418e-ac28-9043ca92fc49
