apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  labels:
    app: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: apache/nifi:2.0.0
        ports:
        - containerPort: 8443  # Porta HTTPS do NiFi
        env:
        - name: NIFI_WEB_HTTPS_PORT
          value: "8443"  # Certifique-se de que HTTPS está ativo
        - name: NIFI_WEB_HTTPS_HOST
          value: "0.0.0.0"  # Escutando em todos os endereços
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: nifi-service
spec:
  selector:
    app: nifi
  ports:
    - protocol: TCP
      port: 8443      # Porta interna para o pod/container
      targetPort: 8443
  type: ClusterIP  # Usando ClusterIP para port-forward
