apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-login-cluster
  namespace: keycloak-login-cluster
  labels:
    name: keycloak-login
spec:
  replicas: 3
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      serviceAccountName: jgroups-kubeping-service-account
      containers:
      - name: keycloak
        image: jboss/keycloak:10.0.1
        env:
        - name: KEYCLOAK_HOSTNAME
          value: keycloak.tylbr.com
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_LOGLEVEL
          value: DEBUG
        - name: ROOT_LOGLEVEL
          value: DEBUG
        - name: KEYCLOAK_USER
          value: keycloak-admin
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: postgres 
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-login-cluster
              key: postgres_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-login-cluster
              key: postgres_password
        - name: DB_DATABASE
          value: keycloak
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: kubernetes.KUBE_PING
        - name: JGROUPS_DISCOVERY_PROPERTIES
          value: port_range=0,dump_requests=true
        - name: KUBERNETES_NAMESPACE
          value: "keycloak-login-cluster"
        - name: KUBERNETES_SERVICE_HOST
          value: "34B6C7C40109181BC826366EF436E410.eks.amazonaws.com"
        - name: connectTimeout
          value: "600000"
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-login-cluster
              key: keycloak_password
        - name: remoteTimeout
          value: "600000"
        resources:
          limits:
            memory: "2048Mi"
          requests:
            memory: "1024Mi"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
