kind: Service
apiVersion: v1
metadata:
  name: keycloak-login-cluster
  namespace: keycloak-login-cluster
  labels:
    app: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443