 ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis-singlenode-APLICACAO
  namespace: NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
  storageClassName: "encrypted-gp2"
---
apiVersion: v1
data:
  redis-config: |
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    appendonly yes
    save 90 1
kind: ConfigMap
metadata:
  name: redis-config-APLICACAO
  namespace: NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-APLICACAO
  name: redis-APLICACAO
  namespace: NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-APLICACAO
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-APLICACAO
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: group-instance
                operator: In
                values:
                - redis
      containers:
      - image: redis:5.0.4
        imagePullPolicy: IfNotPresent
        name: redis-APLICACAO
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
          protocol: TCP
        resources: 
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /redis-master
          name: config
      tolerations:
      - effect: NoSchedule
        key: group-instance
        operator: Equal
        value: redis
      volumes:
      - name: config
        configMap:
          name: redis-config-APLICACAO
          items:
          - key: redis-config
            path: redis.conf
      - name: data
        persistentVolumeClaim:
          claimName: pvc-redis-singlenode-APLICACAO
---
apiVersion: v1
kind: Service
metadata:
  name: redis-APLICACAO-service
  namespace: NAMESPACE
  labels:
    app: redis-APLICACAO
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-APLICACAO-service
  selector:
    app: redis-APLICACAO
